In [2]:
import pandas as pd

In [3]:
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import scale

1. Загрузите выборку

In [4]:

data = pd.read_csv("wine.data", header=None)
data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

2. Извлеките из данных признаки и классы. Класс записан в первом столбце (три варианта), признаки в столбцах со второго по последний.

In [5]:
X = data.iloc[:, 1:]
y = data.iloc[:, 0]
X, y

(        1     2     3     4    5     6     7     8     9      10    11    12  \
 0    14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04  3.92
 1    13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05  3.40
 2    13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03  3.17
 3    14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86  3.45
 4    13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04  2.93
 ..     ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   ...
 173  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64  1.74
 174  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70  1.56
 175  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59  1.56
 176  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60  1.62
 177  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61  1.60

        13
 0    1065
 1    1050
 2    1185
 3    1480
 4     735
 ..    ...
 173   740
 174   750
 175   835
 176   840
 177   560

 [178 rows x 13 columns],
 0      1
 1      1
 2      1
 3      1
 4      1
       ..
 173    3
 174    3
 175    3
 176    3
 177    3
 Name: 0, Length: 178, dtype: int64)

3. Оценку качества необходимо провести методом кросс-валидации по 5 блокам (5-fold). Создайте генератор разбиений, который перемешивает выборку перед формированием блоков. Для воспроизводимости результата, создавайте генератор KFold с фиксированным параметром random_state=42. В качестве меры качества используйте долю верных ответов (accuracy).

In [6]:
cross_val = KFold(n_splits = 5, shuffle = True, random_state=42)
cross_val

KFold(n_splits=5, random_state=42, shuffle=True)

4. Найдите точность классификации на кросс-валидации для метода k ближайших соседей (sklearn.neighbors.KNeighborsClassifier), при k от 1 до 50. При каком k получилось оптимальное качество? Чему оно равно (число в интервале от 0 до 1)? Данные результаты и будут ответами на вопросы 1 и 2.

In [7]:
scores = []
for k in range(1, 50+1):
  classif = KNeighborsClassifier(n_neighbors=k)
  scores.append(cross_val_score(classif, X, y, cv=cross_val, scoring='accuracy'))

print(pd.DataFrame(scores).mean().sort_values().index[-1] + 1, pd.DataFrame(scores).mean().sort_values().iloc[-1])

1 0.7727777777777777

5. Произведите масштабирование признаков с помощью функции sklearn.preprocessing.scale. Снова найдите оптимальное k на кросс-валидации.

6. Какое значение k получилось оптимальным после приведения признаков к одному масштабу? Приведите ответы на вопросы 3 и 4. Помогло ли масштабирование признаков?

In [10]:
X = scale(X)
scores = []
for k in range(1, 51):
    model = KNeighborsClassifier(k)
    scores.append(cross_val_score(model, X, y, cv = cross_val, scoring = 'accuracy'))
pd.DataFrame(scores, range(1, 51)).mean(axis=1).sort_values(ascending= False).head(1)

29    0.977619
dtype: float64